### ISSUE TITLE
`MainCommand.cs` keeps being edited by the formatter

### ISSUE THREAD

**Issue by edwinkortman** [corgibytes/freshli-cli#124]
See this comment https://github.com/corgibytes/freshli-cli/pull/112#discussion_r919069374
![image](https://user-images.githubusercontent.com/7047894/178561870-de05b166-7605-4874-803e-86edd0d038cc.png)

For some reason, the linter see it as okay and then the formatter edits it anyway or vice versa. Investigate why this is happening.

**Comment by CodeMouse92** [comment]
The change is being made by `dotnet jb cleanupcode`, but flagged by `dotnet format --verify-no-changes`.

The quick fix is to run `dotnet format` *after* `dotnet jb cleanup` in `bin/format.rb`, so the order of lint checking and the order of format changing matches. This is probably a good idea anyway.

However, the above fix only works because it'll make and revert the change to `MainCommand.cs`. We will still want to figure out what the conflicting rules in `.editorconfig` are.

**Comment by CodeMouse92** [comment]
It would seem that `dotnet verify` is flagging this because of this rule:

```
csharp_new_line_before_open_brace = all
```

However, I cannot seem to make Jetbrains analyzecode/cleanupcode match, even with changing the analogous rules:

```
resharper_brace_style = next_line
resharper_csharp_brace_style = next_line
resharper_csharp_initializer_braces = next_line
```

The setting continues to thrash, even after cleaning the cache.
