### ISSUE TITLE
Calling `freshli git clone ..` twice in a row, results in a git error

### ISSUE THREAD

**Issue by edwinkortman** [corgibytes/freshli-cli#133]
Found here: 
https://github.com/corgibytes/freshli-cli/pull/116/commits/fb96ad9d4625e411c88d04120bbc507d0c174a12

The error:
![image](https://user-images.githubusercontent.com/7047894/179217118-2b280296-897d-4433-ad25-f0fd4f9da434.png)

To reproduce (call the command twice in a row):
```shell
git clone https://github.com/corgibytes/freshli-fixture-csharp-test.git
git clone https://github.com/corgibytes/freshli-fixture-csharp-test.git
```

**Comment by CodeMouse92** [comment]
Aha. I see what's going on here. This will only occur if you don't specify a branch, because then it doesn't know what to pull the second time you call.

The way around this is to ensure that, in the function that handles pulling, if the branch is not specified, we fetch the current branch with `git branch --show-current` and use that in `git pull origin <branch>`.

**Comment by edwinkortman** [comment]
Good suggestion, thanks! :-)

**Comment by CodeMouse92** [comment]
Yeah, the initial invocation command works without a branch because it runs `git clone` and optionally `git checkout`, but the second invocation runs `git pull origin <branch>`, wherein it has a fit and a half.
